{% set name = "perl-list-binarysearch" %}
{% set version = "0.25" %}
{% set sha256 = "c8113071bd6040035ee8ab01cf1b72a910574192f1d179102ae775a973f2e82a" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: List-BinarySearch-0.25.tar.gz
  url: https://cpan.metacpan.org/authors/id/D/DA/DAVIDO/List-BinarySearch-0.25.tar.gz
  sha256: {{ sha256 }}

# If this is a new build for the same version, increment the build
# number. If you do not include this key, it defaults to 0.
build:
  number: 0

requirements:
  build:
    - perl ==5.22.0.*
    - perl-extutils-makemaker
    #- perl-test-more

  run:
    - perl ==5.22.0.*

test:
  # Perl 'use' tests
  imports:
    - List::BinarySearch
    - List::BinarySearch::PP

  # You can also put a file called run_test.pl (or run_test.py) in the recipe
  # that will be run at test time.

about:
  home: http://metacpan.org/pod/List::BinarySearch
  license: perl_5
  summary: 'Binary Search within a sorted array.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
